

function Donate() {

  return (
    <div class="card border-info">
      <div class="card-header">Donations and Work</div>
      <div class="card-body">
        <p>Every donation is truly appreciated!</p>
        <p>I am offering self-hosted and mobile apps development for a small price.
          The Open Source apps I created are all human-coded, not generated by AI.</p>
      </div>
    </div>
  )
}

export default Donate
