// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/godlev/LANnventory"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activity": {
            "get": {
                "description": "Retrieve recent host activity events ordered by Date descending, then ID descending.\nFirst page requests omit beforeDate and beforeId. To request the next page, send the Date and ID from the final event returned by the previous page as beforeDate and beforeId.\nCursor pagination requires both beforeDate and beforeId. beforeDate must use YYYY-MM-DD HH:mm:ss, beforeId must be greater than 0, and nonzero legacy offset cannot be combined with a cursor. offset=0 with a cursor is accepted.\nLegacy offset pagination remains supported when beforeDate and beforeId are omitted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get recent activity",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Event limit from 1 to 100. Defaults to 20.",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Legacy event offset, 0 or greater. Used only when beforeDate and beforeId are omitted.",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor event date in YYYY-MM-DD HH:mm:ss format. Requires beforeId.",
                        "name": "beforeDate",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Cursor event ID, greater than 0. Requires beforeDate.",
                        "name": "beforeId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "all",
                            "connectivity",
                            "changes"
                        ],
                        "type": "string",
                        "description": "Event category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "discovered",
                            "online",
                            "offline",
                            "known",
                            "unknown",
                            "device-type-changed"
                        ],
                        "type": "string",
                        "description": "Repeatable event type filter",
                        "name": "eventType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repeatable MAC address filter",
                        "name": "mac",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HostEvent"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query or cursor parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Database query failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/activity/devices": {
            "get": {
                "description": "Retrieve devices represented in current hosts and retained activity events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get activity device filter options",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ActivityDeviceOption"
                            }
                        }
                    },
                    "500": {
                        "description": "Database query failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/activity/stats": {
            "get": {
                "description": "Retrieve faceted retained activity event counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get activity event stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repeatable MAC address filter",
                        "name": "mac",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ActivityStats"
                        }
                    },
                    "500": {
                        "description": "Database query failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/all": {
            "get": {
                "description": "Retrieve all hosts from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Get all hosts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Host"
                            }
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "Returns the current configuration used by the app",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get application configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Conf"
                        }
                    }
                }
            }
        },
        "/config/": {
            "post": {
                "description": "Update general UI and server configuration from a form submission.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Save general configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bind host",
                        "name": "host",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bind port",
                        "name": "port",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Theme name",
                        "name": "theme",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "dark",
                            "light"
                        ],
                        "type": "string",
                        "description": "Color mode",
                        "name": "color",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Legacy local node-bootstrap URL",
                        "name": "node",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Notification URL. Leave blank to keep configured secret.",
                        "name": "shout",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Truthy value clears the stored notification URL",
                        "name": "clear_shout",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to referrer",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to write config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config/color": {
            "post": {
                "description": "Update the UI color mode. JSON is the documented API request format; form data is also accepted for UI compatibility.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Save color mode",
                "parameters": [
                    {
                        "description": "Color payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.colorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Conf"
                        }
                    },
                    "400": {
                        "description": "Invalid color",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to write config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config/retention": {
            "post": {
                "description": "Update presence and connectivity event retention windows. JSON is the documented API request format; form data is also accepted for UI compatibility.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Save retention settings",
                "parameters": [
                    {
                        "description": "Retention payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.retentionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Conf"
                        }
                    },
                    "400": {
                        "description": "Invalid retention value",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to write config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config_influx/": {
            "post": {
                "description": "Update InfluxDB integration settings from a form submission.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Save InfluxDB configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truthy value enables InfluxDB",
                        "name": "enable",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "InfluxDB address",
                        "name": "addr",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "InfluxDB token. Leave blank to keep configured secret.",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Truthy value clears the stored InfluxDB token",
                        "name": "clear_influx_token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "InfluxDB organization",
                        "name": "org",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "InfluxDB bucket",
                        "name": "bucket",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Truthy value skips TLS verification",
                        "name": "skip",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to referrer",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to write config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config_prometheus/": {
            "post": {
                "description": "Update Prometheus integration settings from a form submission.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Save Prometheus configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truthy value enables Prometheus metrics",
                        "name": "enable",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to referrer",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to write config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config_settings/": {
            "post": {
                "description": "Update scan and database settings from a form submission, then restart scanning.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Save scan and database settings",
                "parameters": [
                    {
                        "enum": [
                            "debug",
                            "info",
                            "warn",
                            "error"
                        ],
                        "type": "string",
                        "description": "Log level",
                        "name": "log",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "arp-scan arguments",
                        "name": "arpargs",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Interfaces to scan",
                        "name": "ifaces",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "sqlite",
                            "postgres"
                        ],
                        "type": "string",
                        "description": "Database backend",
                        "name": "usedb",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PostgreSQL connection URL. Leave blank to keep configured secret.",
                        "name": "pgconnect",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Truthy value clears the stored PostgreSQL connection URL",
                        "name": "clear_pgconnect",
                        "in": "formData"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Scan interval in seconds",
                        "name": "timeout",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Presence history retention in hours",
                        "name": "trim",
                        "in": "formData"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Connectivity event retention in hours",
                        "name": "connectivity_retention",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Repeatable static ARP result strings",
                        "name": "arpstrs",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to referrer",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid settings",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to reconnect database or write config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/edit/{id}/{name}/{known}": {
            "get": {
                "description": "Update a host's name and optionally toggle its \"known\" status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Edit host",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "New name for the host",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pass 'toggle' to flip the known/unknown status",
                        "name": "known",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns OK without triggering scans or mutations",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "description": "Retrieve the complete history of all hosts. Not recommended, the output can be a lot",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Get full history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Host"
                            }
                        }
                    }
                }
            }
        },
        "/history/{mac}": {
            "get": {
                "description": "Retrieve the latest history entries for a specific host by MAC address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Get history by MAC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MAC address of the host",
                        "name": "mac",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of history entries to return",
                        "name": "num",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Host"
                            }
                        }
                    }
                }
            }
        },
        "/history/{mac}/{date}": {
            "get": {
                "description": "Retrieve history for a specific host on a given date\nThe date format is flexible and can be:\n- Year only: ` + "`" + `2025` + "`" + `\n- Year + month: ` + "`" + `2025-09` + "`" + `\n- Full date: ` + "`" + `2025-09-06` + "`" + `\n- Full timestamp: ` + "`" + `2025-09-06 00:58:26` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Get history by date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MAC address of the host",
                        "name": "mac",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date filter (supports YYYY, YYYY-MM, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss)",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Host"
                            }
                        }
                    }
                }
            }
        },
        "/host/add/{mac}": {
            "get": {
                "description": "Add host by MAC, with optional Name, IP, Hardware\nReturns ` + "`" + `models.Host` + "`" + ` with this MAC form DB, either just added or existing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Add host manually",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host MAC",
                        "name": "mac",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IP",
                        "name": "ip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Hardware",
                        "name": "hw",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Host"
                        }
                    }
                }
            }
        },
        "/host/del/{id}": {
            "get": {
                "description": "Remove a host from the database by its unique ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Delete host",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/host/{id}": {
            "get": {
                "description": "Retrieve detailed information about a host by its unique ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Get host by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Host"
                        }
                    }
                }
            }
        },
        "/host/{id}/activity": {
            "get": {
                "description": "Retrieve recent host activity events for a host ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get recent activity for one host",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Event limit from 1 to 100. Defaults to 20.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HostEvent"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid host ID or limit",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Database query failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/host/{id}/type": {
            "patch": {
                "description": "Update only a host's manually assigned device type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hosts"
                ],
                "summary": "Set host device type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Device type payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Host"
                        }
                    }
                }
            }
        },
        "/notify_test": {
            "get": {
                "description": "Trigger a test notification to verify notification settings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Send test notification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/port/{addr}/{port}": {
            "get": {
                "description": "Check whether a given TCP port on an address is open or closed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Check port state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP address or hostname",
                        "name": "addr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Port number",
                        "name": "port",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "true if open, false if closed",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/rescan": {
            "get": {
                "description": "Manually trigger rescan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Rescan all interfaces now",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status/{iface}": {
            "get": {
                "description": "Retrieve summary statistics of hosts, optionally filtered by interface",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get network status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Interface name (omit for all interfaces)",
                        "name": "iface",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Stat"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current running version of the application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get application version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wol/{mac}": {
            "get": {
                "description": "Send a magic packet to wake up a host by its MAC address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Send Wake-on-LAN packet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MAC address of the host",
                        "name": "mac",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "true if sent successfully",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.colorRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                }
            }
        },
        "api.retentionRequest": {
            "type": "object",
            "properties": {
                "connectivityRetention": {
                    "type": "integer"
                },
                "presenceRetention": {
                    "type": "integer"
                }
            }
        },
        "models.ActivityDeviceOption": {
            "type": "object",
            "properties": {
                "deviceType": {
                    "type": "string"
                },
                "exists": {
                    "type": "boolean"
                },
                "hostID": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ActivityStats": {
            "type": "object",
            "properties": {
                "deviceTypeChanged": {
                    "type": "integer",
                    "format": "int64"
                },
                "discovered": {
                    "type": "integer",
                    "format": "int64"
                },
                "known": {
                    "type": "integer",
                    "format": "int64"
                },
                "offline": {
                    "type": "integer",
                    "format": "int64"
                },
                "online": {
                    "type": "integer",
                    "format": "int64"
                },
                "total": {
                    "type": "integer",
                    "format": "int64"
                },
                "unknown": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "models.Conf": {
            "type": "object",
            "properties": {
                "arpArgs": {
                    "type": "string"
                },
                "arpStrs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "color": {
                    "type": "string"
                },
                "confPath": {
                    "type": "string"
                },
                "connectivityRetention": {
                    "type": "integer"
                },
                "dbpath": {
                    "type": "string"
                },
                "dirPath": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "ifaces": {
                    "type": "string"
                },
                "influxAddr": {
                    "type": "string"
                },
                "influxBucket": {
                    "type": "string"
                },
                "influxEnable": {
                    "description": "InfluxDB",
                    "type": "boolean"
                },
                "influxOrg": {
                    "type": "string"
                },
                "influxSkipTLS": {
                    "type": "boolean"
                },
                "influxToken": {
                    "type": "string"
                },
                "logLevel": {
                    "type": "string"
                },
                "nodePath": {
                    "type": "string"
                },
                "pgconnect": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "prometheusEnable": {
                    "description": "Prometheus",
                    "type": "boolean"
                },
                "shoutURL": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                },
                "timeout": {
                    "type": "integer"
                },
                "trimHist": {
                    "type": "integer"
                },
                "useDB": {
                    "description": "PostgreSQL",
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.Host": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "deviceType": {
                    "type": "string"
                },
                "dns": {
                    "type": "string"
                },
                "hw": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "iface": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "known": {
                    "type": "integer"
                },
                "mac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "now": {
                    "type": "integer"
                }
            }
        },
        "models.HostEvent": {
            "type": "object",
            "properties": {
                "DateUTC": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deviceType": {
                    "type": "string"
                },
                "eventType": {
                    "type": "string"
                },
                "hostID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "iface": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "newValue": {
                    "type": "string"
                },
                "oldValue": {
                    "type": "string"
                }
            }
        },
        "models.Stat": {
            "type": "object",
            "properties": {
                "known": {
                    "type": "integer"
                },
                "offline": {
                    "type": "integer"
                },
                "online": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "unknown": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0-beta.2",
	Host:             "",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "LANnventory API",
	Description:      "Local network inventory and monitoring application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
